type: app
database: pg
language: slang
model: granite

# list of tasks to be run by `amber watch`
watch:
  # NOTE: names that match crystal commands are special (e.g. run, spec)
  run:
    # commands will be joined with && (join them yourself if need || or ;)
    build_commands:
      - mkdir -p bin
      - crystal build ./src/backend.cr -o bin/backend
    run_commands:
      - bin/backend
    include:
      - ./config/**/*.cr
      - ./src/**/*.cr
  spec:
    run_commands:
      - crystal spec
    include:
      - ./spec/**/*.cr
